### PR TITLE
Beginners: Add gui applications on docker tutorial

### PR DESCRIPTION
**Pull request by akshitgrover**
@collabnix @ajeetraina
This PR adds a reference in the beginners track, On why and how to run desktop applications in a docker container.
Please review it for any changes.

### CODE REVIEW

**Comment by ajeetraina** [comment]
LGTM.

Nice topic and good piece of writing. Keep it up.

**Comment by akshitgrover** [comment]
So is it good to merge?

**Comment by ajeetraina** [comment]
Yes, I will be merging it shortly.


Regards,
Ajeet

**Review by collabnix — APPROVED** [review]
LGTM

**Pull request merged**
