### PR TITLE
Fix Run instruction link

### LINKED ISSUE #398: Wrong link
My students who observed this issue.

When you access https://dockerlabs.collabnix.com/workshop/docker/ in Getting Started with Dockerfile the URL #Lab7 send you to https://dockerlabs.collabnix.com/beginners/dockerfile/Lab-7-Create-an-image-with-EXPOSE-instruction.html but when you practicing Lab#6 in end the URL send you to https://dockerlabs.collabnix.com/beginners/dockerfile/Lab%237:RUN_instruction.html

And congratulation for this material

### PR DESCRIPTION
**Pull request by mariosimao**
Closes #398

### CODE REVIEW

**Comment by mariosimao** [comment]
@collabnix @sangam14 is this repository active?

**Comment by sangam14** [comment]
@mariosimao yup this repo is active!

**Comment by mariosimao** [comment]
@sangam14 , I made a small PR to fix a reported issue. Could you please approval the workflow?

**Review by sangam14 — APPROVED** [review]

**Comment by sangam14** [comment]
Thanks @mariosimao for improving site ! & Contribution

**Pull request merged**
